package x

// Basic types for X Windows interface used by the autogenerated types

type VALUE        uint32
type BYTE         uint8
type INT8         int8
type INT16        int8
type INT32        int32
type CARD8        uint8
type CARD16       uint16
type CARD32       uint32
type XID          uint32
type BOOL         uint8
type STRING8    []CARD8

// Used only for padding bytes
type PADDING      uint8
